# coding: utf-8

"""
    BRP historie bevragen

    API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_historie_client.models.adres_voorkomen import AdresVoorkomen

class TestAdresVoorkomen(unittest.TestCase):
    """AdresVoorkomen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdresVoorkomen:
        """Test AdresVoorkomen
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdresVoorkomen`
        """
        model = AdresVoorkomen()
        if include_optional:
            return AdresVoorkomen(
                verblijfadres = brp_historie_client.models.verblijfadres_binnenland.VerblijfadresBinnenland(
                    officiele_straatnaam = '', 
                    korte_straatnaam = '', 
                    huisnummer = 14, 
                    huisletter = 'a', 
                    huisnummertoevoeging = 'bis', 
                    aanduiding_bij_huisnummer = brp_historie_client.models.waardetabel.Waardetabel(
                        code = '6030', 
                        omschrijving = 'Nederland', ), 
                    postcode = '2341SX', 
                    woonplaats = 'Duiven', 
                    in_onderzoek = null, ),
                functie_adres = brp_historie_client.models.waardetabel.Waardetabel(
                    code = '6030', 
                    omschrijving = 'Nederland', ),
                adresseerbaar_object_identificatie = '0226010000038820',
                nummeraanduiding_identificatie = '0518200000366054',
                gemeente_van_inschrijving = brp_historie_client.models.waardetabel.Waardetabel(
                    code = '6030', 
                    omschrijving = 'Nederland', ),
                datum_van = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                datum_tot = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                verblijft_niet_op_adres_vanaf = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                in_onderzoek = None,
                adressering = brp_historie_client.models.adressering_binnenland.AdresseringBinnenland(
                    adresregel1 = 'Kappeyne v d Cappellostr 26A-3', 
                    adresregel2 = '1234AA Nootdorp', 
                    in_onderzoek = null, )
            )
        else:
            return AdresVoorkomen(
        )
        """

    def testAdresVoorkomen(self):
        """Test AdresVoorkomen"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
