# coding: utf-8

"""
    BRP historie bevragen

    API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_historie_client.models.locatie_voorkomen import LocatieVoorkomen

class TestLocatieVoorkomen(unittest.TestCase):
    """LocatieVoorkomen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocatieVoorkomen:
        """Test LocatieVoorkomen
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocatieVoorkomen`
        """
        model = LocatieVoorkomen()
        if include_optional:
            return LocatieVoorkomen(
                datum_van = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                datum_tot = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                functie_adres = brp_historie_client.models.waardetabel.Waardetabel(
                    code = '6030', 
                    omschrijving = 'Nederland', ),
                verblijfadres = brp_historie_client.models.verblijfadres_locatie.VerblijfadresLocatie(
                    locatiebeschrijving = 'Naast de derde brug', 
                    in_onderzoek = null, ),
                gemeente_van_inschrijving = brp_historie_client.models.waardetabel.Waardetabel(
                    code = '6030', 
                    omschrijving = 'Nederland', ),
                verblijft_niet_op_adres_vanaf = brp_historie_client.models.abstract_datum.AbstractDatum(
                    type = '', 
                    lang_formaat = 'pr1c2v7s6dju', ),
                in_onderzoek = None,
                adressering = brp_historie_client.models.adressering_binnenland.AdresseringBinnenland(
                    adresregel1 = 'Kappeyne v d Cappellostr 26A-3', 
                    adresregel2 = '1234AA Nootdorp', 
                    in_onderzoek = null, )
            )
        else:
            return LocatieVoorkomen(
        )
        """

    def testLocatieVoorkomen(self):
        """Test LocatieVoorkomen"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
