# coding: utf-8

"""
    BRP historie bevragen

    API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_historie_client.models.adressering_buitenland import AdresseringBuitenland

class TestAdresseringBuitenland(unittest.TestCase):
    """AdresseringBuitenland unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdresseringBuitenland:
        """Test AdresseringBuitenland
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdresseringBuitenland`
        """
        model = AdresseringBuitenland()
        if include_optional:
            return AdresseringBuitenland(
                adresregel1 = 'Kappeyne v d Cappellostr 26A-3',
                adresregel2 = '1234AA Nootdorp',
                adresregel3 = 'Selangor',
                land = brp_historie_client.models.waardetabel.Waardetabel(
                    code = '6030', 
                    omschrijving = 'Nederland', ),
                in_onderzoek = None
            )
        else:
            return AdresseringBuitenland(
        )
        """

    def testAdresseringBuitenland(self):
        """Test AdresseringBuitenland"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
